# Site
title: daiyi
subtitle:
description: it's my blorg
author: daiyi
language: en
timezone: America/Los_Angeles # Europe/Berlin

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://daiyi.co/blog
root: /blog/
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: c
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - comments.md
  - "**.json"
exclude:
  - comments.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: etc
category_map:
  "mica's journal": mica
tag_map:

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  html: true # don't escape html
  breaks: false
  plugins:
    - markdown-it-footnote
  anchors:
    # Minimum level for ID creation. (Ex. h2 to h6)
    level: 2
    # A suffix that is prepended to the number given if the ID is repeated.
    collisionSuffix: "v"
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: true
    # Class used for the permalink anchor tag.
    permalinkClass: header-anchor
    # Set to 'right' to add permalink after heading
    permalinkSide: "left"
    # The symbol used to make the permalink
    permalinkSymbol: ">"
    # Transform anchor to (1) lower case; (2) upper case
    case: 0
    # Replace space with a character
    separator: "-"

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
theme: splitter

# Deployment
# This is the manual deploy summoned with `hexo deploy`.
# The github actions hook is different, it uses a fancy package
deploy:
  type: git
  repo: git@github.com:daiyi/blog.git
  branch: gh-pages
  message: "deployed: {{ now('YYYY-MM-DD HH:mm:ss') }}"

feed:
  type: rss2
  path: rss2.xml
  limit: false
  content: true
  excerpt_frontmatter_key: summary

# css processing
stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ""
    basePath: .
  plugins: "nib"

# category descriptions
category_config:
  "mica's journal":
    description: Hi I'm Mica, I am a dog. I run the show as CEO. I live with my CTO (Chief Treats Officer) daiyi and my CMO (Chief Marco Officer) Marco. daiyi writes my story because I can't use a computer. I like to eat squirrels, sleep all day, send with mountain bikes, and bag peaks with my bff yelly.
    image: "mica.jpg"

# map plugin
# check the scripts folder for leaflet.js
# baseLayers: https://osmlab.github.io/editor-layer-index/
leaflet:
  baseLayer: "https://caltopo.s3.amazonaws.com/topo/{z}/{x}/{y}.png"
  attribution: "Map data © USGS. Hosted by Caltopo"
