# Header
links:
  - name: archive
    url: https://daiyi.co/blog/archives
  - name: about
    url: https://daiyi.co
  - name: twitter
    url: https://twitter.com/daiyitastic
  - name: email updates
    url: https://buttondown.email/daiyi

footer:
  - name: rss
    url: https://daiyi.co/blog/rss2.xml
  - name: archive
    url: https://daiyi.co/blog/archives

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: daiyitastic

# comments
markdown_comments:
  repo_root: https://github.com/daiyi/blog/blob/master/source/_posts/
  file_name: _comments.yaml
  email: comments@daiyi.co
  endpoint: https://comment-pr.vercel.app/api # prod
  # endpoint: http://localhost:3002/api # dev
