# Header
links:
  - name: about
    url: https://daiyi.co
  - name: twitter
    url: https://twitter.com/daiyitastic

footer:
  - name: archive
    url: https://daiyi.co/blog/archives
  - name: email updates
    url: https://tinyletter.com/daiyi
  - name: rss
    url: https://daiyi.co/blog/rss2.xml

# Content
excerpt_link: Read More
fancybox: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: daiyitastic

# comments
markdown_comments:
  repo_root: https://github.com/daiyi/blog/blob/master/source/_posts/
  file_name: _comments.yaml
  email: comments@daiyi.co
